### ISSUE TITLE
[FR]: support webpack 4

### ISSUE THREAD

**Issue by jbedard** [aspect-build/rules_webpack#119]
### What is the current behavior?

Worker crashes with webpack 4, not testing with webpack 4.

### Describe the feature

Webpack 4 is still widely used and probably worth supporting.

WIP showing some potential changes: https://github.com/aspect-build/rules_webpack/pull/124

**Comment by alexeagle** [comment]
Do you have some client code that updates the worker, at least we could stash in a PR here so we have a chance of using it to resolve this issue.
