### ISSUE TITLE
Promote from "experimental"

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_webpack#12]
We have one client successfully using this and are ready to commit to keeping the repo active.

**Comment by loudmouth** [comment]
Hey Aspect team and Bazel JavaScript community 👋 

I was curious about the experimental status of this project. I've observed the activity here increase a bit, but I'm still hesitant to take a stab at integrating these rules in our project given the disclaimer on the README. Are there any shareable thoughts on the likelihood that this projects graduates from experimental to active maintenance?
