### ISSUE TITLE
Typescript defined config file

### ISSUE THREAD

**Issue by arobinson** [aspect-build/rules_webpack#33]
I've been using webpack with a typescript config file. Unfortunately, the webpack_bundle rule is not allowing this:

```
(14:32:23) ERROR: BUILD.bazel:130:15: in webpack_config attribute of webpack_bundle rule //:bundle_dev: source file '//:webpack-dev-build.config.ts' is misplaced here (expected .js)
```

Webpack supports typescript itself:
https://webpack.js.org/configuration/configuration-languages/#typescript

Just looks like an incorrect restriction from the Bazel rule

**Comment by jbedard** [comment]
Have you tried compiling that ts first and passing the compiled js? Normally any typescript would be compiled to js with `ts_project` before being passed to webpack, and I think the same should be done for config files.

**Comment by arobinson** [comment]
I'm not talking about the code being packed, I'm referring to the actual webpack configuration file being a Typescript file. The Bazel rule is only allowing .js, but Webpack supports multiple formats, at least .js and .ts files. So I'm just requesting the attribute of the Bazel rule to permit .ts as a file extension for the configuration file

**Comment by jbedard** [comment]
I'm talking about the webpack config file.

Outside bazel typescript is normally compiled with a webpack plugin, I assume the webpack config as typescript is the same. In bazel (or the aspect rules_* at least) the typescript is compiled by `ts_project` and webpack is passed the resulting .js files, webpack itself doesn't need to know anything about typescript.

Can you compile the webpack config into .js before passing it into webpack?

**Comment by arobinson** [comment]
Webpack supports typescript config files, for the reason that you don't HAVE to transpile it to JavaScript first. All the bazel rule needs to do is add `.ts` as a supported file extension. So someone could transpile it first, but that is a whole lot more work than just allowing a ts file to be passed as a config file. As for:

> webpack itself doesn't need to know anything about typescript.

It already has code to support typescript config files directly without any other help. It has supported Typescript types [since 2020](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#typescript-typings) 

Why is there a pushback for such a simple change.

Just change:
```
    "webpack_config": attr.label(
        doc = """Webpack configuration file.
        
See https://webpack.js.org/configuration/""",
        allow_single_file = [".js"],
        mandatory = False,
    ),
 ```
to:
```
    "webpack_config": attr.label(
        doc = """Webpack configuration file.
        
See https://webpack.js.org/configuration/""",
        allow_single_file = [".js", ".ts"],
        mandatory = False,
    ),
```

**Comment by jbedard** [comment]
If that's all that's needed it is probably fine, as long as we don't need to configure typescript within webpack. I'd still think it's better to let bazel compile it and cache it but one file is pretty minor 🤷
