### ISSUE TITLE
Consider adding a LICENSE file

### ISSUE THREAD

**Issue by n1c00o** [aspect-build/rules_webpack#43]
Licenses are important in modern software development, and especially when dealing with third party dependencies.

For organisations, it is important to respect licenses since misusing a library can result in *bad things*.

The need for a `LICENSE` file is also a good practice when using Bazel since the, for now experimental, [rules_license](https://github.com/bazelbuild/rules_license) can be used to check for licenses and so on.

> More at <https://opensource.google/documentation/reference/thirdparty/licenses>.

Since a lot of "official" rules are using the Apache License 2.0 (SPDX: Apache-2.0), it would be a great idea to also use it?

**Comment by n1c00o** [comment]
I noticed that the template repository includes a LICENSE file with the Apache License 2.0, you could easily grab this file here

**Comment by gregmagolan** [comment]
Thanks for catching that. All our OSS rule sets are Apache 2. I'll add the missing license.

**Comment by gregmagolan** [comment]
Resolved with https://github.com/aspect-build/rules_webpack/commit/203668bd90937e334829d6d117702a109c9261fb

**Comment by n1c00o** [comment]
Thanks!
