### ISSUE TITLE
[Bug]: webpack_devserver rule has hardcoded name ("devserver")

### ISSUE THREAD

**Issue by gregjacobs** [aspect-build/rules_webpack#65]
### What happened?

Looks like the `webpack_devserver` macro doesn't respect the 'name' arg and has been hardcoded to the value "devserver". Oops :)

```starlark
js_run_devserver(
    name = "devserver",
    #       ^----
)   
```

https://github.com/aspect-build/rules_webpack/blob/v0.5.1/webpack/private/webpack_devserver.bzl#L50

### Version

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: **rules_webpack v0.5.1**

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Hey. Catching up on issues after BazelCon. Thanks for pointing this one out. Will put up a PR.

**Comment by gregmagolan** [comment]
Fixed. I'll be cutting a rules_webpack release shortly.

**Comment by gregjacobs** [comment]
Awesome, thanks for fixing this! :)
