### ISSUE TITLE
[FR]: `chdir` support

### ISSUE THREAD

**Issue by LavaToaster** [aspect-build/rules_webpack#75]
### What is the current behavior?

Packages like `react-scripts` cannot find the correct `package.json` because it sits in a folder a level or many up from the root dir.

### Describe the feature

I currently have packages (mainly `react-scripts`) that expect the webpack process to be in a specific folder to read expected files correctly.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by thesayyn** [comment]
fixed by #76
